# Generated by Django 4.2.20 on 2025-04-21 20:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название документа')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('version', models.DecimalField(decimal_places=1, default=1.0, max_digits=3, verbose_name='Версия документа')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_model_authors', to=settings.AUTH_USER_MODEL, verbose_name='ID пользователя, который создал')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_model_updaters', to=settings.AUTH_USER_MODEL, verbose_name='ID пользователя, который обновил')),
            ],
        ),
    ]
