# Generated by Django 4.2.20 on 2025-05-05 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_document_alter_documents_options_block'),
    ]

    operations = [
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название задачи')),
                ('description', models.TextField(verbose_name='Описание задачи')),
                ('urgency', models.CharField(choices=[('low', 'Низкая'), ('medium', 'Средняя'), ('high', 'Высокая')], max_length=10, verbose_name='Срочность')),
                ('priority', models.CharField(choices=[('low', 'Низкий'), ('medium', 'Средний'), ('high', 'Высокий')], max_length=10, verbose_name='Приоритет')),
                ('customer', models.CharField(max_length=200, verbose_name='заказчик (организация)')),
                ('file', models.FileField(blank=True, null=True, upload_to='tasks_files/', verbose_name='Файл')),
                ('deadline', models.DateField(verbose_name='Дедлайн')),
                ('assignee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.developer')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
                'ordering': ['-title'],
            },
        ),
    ]
