# Generated by Django 4.2.20 on 2025-05-05 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_developer_tasks'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='developer',
            options={'ordering': ['name'], 'verbose_name': 'Разработчик', 'verbose_name_plural': 'Разработчики'},
        ),
        migrations.AddField(
            model_name='tasks',
            name='status',
            field=models.CharField(choices=[('in_progress', 'В работе'), ('completed', 'Выполнена'), ('under_review', 'На рассмотрении')], default='under_review', max_length=15, verbose_name='Статус'),
        ),
    ]
