# Generated by Django 4.2.20 on 2025-05-06 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_developer_tasks'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Тема обращения')),
                ('description', models.TextField(verbose_name='Описание обращения')),
                ('customer', models.CharField(max_length=200, verbose_name='заказчик (организация)')),
                ('file', models.FileField(blank=True, null=True, upload_to='tickets_files/', verbose_name='Файл')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания обращения')),
                ('status', models.CharField(choices=[('in_progress', 'В работе'), ('new', 'Новое'), ('decided', 'Решено')], default='new', max_length=15, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Обращение',
                'verbose_name_plural': 'Обращения',
                'ordering': ['-title'],
            },
        ),
        migrations.AlterModelOptions(
            name='developer',
            options={'ordering': ['name'], 'verbose_name': 'Разработчик', 'verbose_name_plural': 'Разработчики'},
        ),
        migrations.AddField(
            model_name='tasks',
            name='status',
            field=models.CharField(choices=[('in_progress', 'В работе'), ('completed', 'Выполнена'), ('under_review', 'На рассмотрении')], default='under_review', max_length=15, verbose_name='Статус'),
        ),
    ]
