# Generated by Django 4.2.20 on 2025-05-14 08:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0005_tickets_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название события')),
                ('description', models.TextField(blank=True, verbose_name='Описание события')),
                ('date', models.DateTimeField(verbose_name='Дата события')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Событие',
                'verbose_name_plural': 'События',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='InternalDocs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название документа')),
                ('description', models.TextField(verbose_name='Описание документа')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания вн. док.')),
                ('file', models.FileField(blank=True, null=True, upload_to='docs_files/', verbose_name='Файл')),
                ('type', models.CharField(choices=[('Приказ', 'Приказ'), ('Справка', 'Справка'), ('Заявление', 'Заявление')], max_length=15, verbose_name='Тип документа')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Внутренний документ',
                'verbose_name_plural': 'Внутренние документы',
            },
        ),
        migrations.AddField(
            model_name='block',
            name='video',
            field=models.FileField(blank=True, upload_to='video/', verbose_name='Видео'),
        ),
        migrations.AddField(
            model_name='tickets',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='block',
            name='block_type',
            field=models.CharField(choices=[('Текст', 'Текст'), ('Изображение', 'Изображение'), ('Видео', 'Видео')], max_length=15),
        ),
        migrations.AlterField(
            model_name='block',
            name='content',
            field=models.TextField(blank=True, verbose_name='Текст документа'),
        ),
        migrations.AlterField(
            model_name='block',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='project.documents'),
        ),
        migrations.AlterField(
            model_name='block',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='customer',
            field=models.CharField(max_length=200, verbose_name='Заказчик (организация)'),
        ),
        migrations.DeleteModel(
            name='Document',
        ),
    ]
