# Generated by Django 4.2.20 on 2025-05-11 15:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0005_tickets_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='customer',
            field=models.CharField(max_length=200, verbose_name='Заказчик (организация)'),
        ),
        migrations.CreateModel(
            name='InternalDocs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название документа')),
                ('description', models.TextField(verbose_name='Описание документа')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания вн. док.')),
                ('file', models.FileField(blank=True, null=True, upload_to='docs_files/', verbose_name='Файл')),
                ('type', models.CharField(choices=[('Приказ', 'Приказ'), ('Справка', 'Справка'), ('Заявление', 'Заявление')], max_length=15, verbose_name='Тип документа')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
        ),
    ]
