# Generated by Django 4.2.20 on 2025-05-12 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_alter_tickets_customer_internaldocs'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='internaldocs',
            options={'verbose_name': 'Внутренний документ', 'verbose_name_plural': 'Внутренние документы'},
        ),
        migrations.AddField(
            model_name='tickets',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий'),
        ),
    ]
