# Generated by Django 4.2.20 on 2025-05-14 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_alter_internaldocs_options_tickets_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'verbose_name': 'Документ', 'verbose_name_plural': 'Документы'},
        ),
        migrations.AddField(
            model_name='block',
            name='video',
            field=models.FileField(blank=True, upload_to='video/', verbose_name='Видео'),
        ),
        migrations.AlterField(
            model_name='block',
            name='block_type',
            field=models.CharField(choices=[('Текст', 'Текст'), ('Изображение', 'Изображение'), ('Видео', 'Видео')], max_length=15),
        ),
        migrations.AlterField(
            model_name='block',
            name='content',
            field=models.TextField(blank=True, verbose_name='Текст документа'),
        ),
        migrations.AlterField(
            model_name='block',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='project.documents'),
        ),
        migrations.AlterField(
            model_name='block',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='document',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Название документа'),
        ),
    ]
